apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: xivstatus-redis
  namespace: xivstatus
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: xivstatus-redis
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: redis
    version: 9.4.1
  values:
    tag: 5.0.5-alpine
    usePassword: false
    master:
      persistence: 
        enabled: false
    slave:
      persistence: 
        enabled: false