apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: xivstatus-monitor
  namespace: xivstatus
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: xivstatus-monitor
  chart:
    git: git@github.com:defrostedtuna/kubernetes-lordran-dev
    path: charts/xivstatus-monitor
    ref: master
  valuesFrom:
  - configMapKeyRef:
      name: xivstatus-monitor
  values:
    configHash: c46ee6147f8fe1ad275992dcb685b3d71b1a6c8f54630137b95d76099b10daf3
    image:
      repository: harbor.uptilt.io/defrostedtuna/xivstatus-monitor
      tag: master-5adebb2
      pullPolicy: Always
      auth: true
      pullSecretsName: harbor-regcred