apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: harbor
  chart:
    repository: https://helm.goharbor.io
    name: harbor
    version: 1.0.0
  values:
    valuesFrom:
    - secretKeyRef:
        name: harbor-helm-chart-config
    imagePullPolicy: Always
    externalURL: https://harbor.uptilt.dev
    FullNameOverride: harbor
    expose:
      type: ingress
      tls:
        enabled: true
        secretName: "harbor-registry-tls-prod"
        notarySecretName: "harbor-notary-tls-prod"
      ingress:
        hosts:
          core: harbor.uptilt.dev
          notary: notary.harbor.uptilt.dev
        annotations:
          ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    persistence:
      enabled: true
      resourcePolicy: "keep"
      persistentVolumeClaim:
        registry:
          existingClaim: pvc-harbor-registry
          storageClass: "-"
          subPath: ""
          accessMode: ReadWriteOnce
          size: 25Gi
        chartmuseum:
          existingClaim: pvc-harbor-chartmuseum
          storageClass: "-"
          subPath: ""
          accessMode: ReadWriteOnce
          size: 10Gi
        database:
          existingClaim: pvc-harbor-database
          storageClass: "-"
          subPath: ""
          accessMode: ReadWriteOnce
          size: 2Gi