apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
  annotations:
    # flux.weave.works/ignore: true
    flux.weave.works/automated: "false"
spec:
  releaseName: sealed-secrets
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: sealed-secrets
    version: 1.2.0
  values:
    image:
      repository: quay.io/bitnami/sealed-secrets-controller
      tag: v0.7.0
      pullPolicy: Always
    crd:
      keep: false