apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uptilt-weather-helm-chart-values
  namespace: uptilt-weather
spec:
  encryptedData:
    values.yaml: AgCnrM2IytDYSFuWtSCeRZzU0wPcJ71w0gJxik0xdCgTlGJumfqADZaP/9oq6hQONwuZrBmqiw9wNQ6fwxTOG0oGb+ga0Q8O2grdbjUIXiTqIvhsMFShNNuaLsnUSfnJfv3AVlzmq9ao0zjkQdlIBIlDgvD2OtxUQW+qQxy1w6MI3qnZEJTMXOJrDbdyAObEjGK9KWZwx6lSzqdtDv1RKSpSZ0f43Q9B2v39M+7m9HDYP9u1bvR3rDNEB6pUaTtoeQVB/p6W4pAHIt4ot6OtdMMUtf8U5lXUf65RBKcqQp68CHGLmCha3pv/BndCMYVEC28GVUb2K/YWCS2cQAbN4DYU2fQMW/LPhnJpKFYM3oiEil/0KFgCpr+tV8d44Y7YHmM1qKMJrrt/zCs48MMO2S7sRoImFwLHGfK69dgoIL3SdCh0JkUlcWh+XSmxE/uLcUqyN06ZWSRjf8Po3D5VhBgYZsZIAZmuq7daWRkbAM/BwgZeRjYtW5/6IaKeawkRVCsTZzQlAop5eNF3z3fULtR8ADYrxhr1FK93+OYwqtZ1lRYeXJ1s/XXld+0j2UXYvETVjCe6PhSrGumGtNe4Ms5Y/EVXQR46h+e3odkWutOcDIlk/cK1LHyYS1Na3oxEU5kDwu8l3BNgs/Y8rSn3XOIZrEq4oiRpn4hPCQsm4YE7QQKZTml3mbBkbpJDHcDn43+eAfO29XQgLZzFhMUO0jLnSpjGYOoc/KTqZ/nIFXmmCuxjjxzsMwlrHSkmk+NoJri3o1D2i1qxzsu41VPoRmPVeiPIMIo4i+1Ct/iGOvWN/kRHyJAx1geLMDlm5wP9/6DcI11cWp+1Vv52eaGkGo1tOJ3qYS3JAve9wI9XHeodiXmZ68pW5FpcLNm5E4c83Zhj+rVZbg==

