apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xivstatus-monitor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "xivstatus-monitor.name" . }}
    helm.sh/chart: {{ include "xivstatus-monitor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "xivstatus-monitor.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "xivstatus-monitor.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- if .Values.image.auth }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretsName }}
    {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NODE_APP_API_HOST
              value: "https://xivstatus-api.uptilt.dev"
            - name: NODE_APP_REDIS_HOST
              value: "xivstatus-redis-master"
            - name: NODE_APP_REDIS_PORT
              value: "6379"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
