apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xivstatus-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "xivstatus-api.name" . }}
    helm.sh/chart: {{ include "xivstatus-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "xivstatus-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "xivstatus-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- if .Values.image.auth }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretsName }}
    {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/status
              port: http
          readinessProbe:
            httpGet:
              path: /api/status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: APP_NAME
              value: {{ .Values.env.appName }}
            - name: APP_ENV
              value: {{ .Values.env.appEnv }}
            - name: APP_KEY
              value: {{ .Values.env.appKey }}
            - name: APP_DEBUG
              value: {{ .Values.env.appDebug }}
            - name: APP_URL
              value: {{ .Values.env.appUrl }}
            - name: LOG_CHANNEL
              value: {{ .Values.env.logChannel }}
            - name: DB_CONNECTION
              value: {{ .Values.env.dbConnection }}
            - name: DB_HOST
              value: {{ .Values.env.dbHost }}
            - name: DB_PORT
              value: {{ .Values.env.dbPort }}
            - name: DB_DATABASE
              value: {{ .Values.env.dbDatabase }}
            - name: DB_USERNAME
              value: {{ .Values.env.dbUsername }}
            - name: DB_PASSWORD
              value: {{ .Values.env.dbPassword }}
            - name: REDIS_HOST
              value: {{ .Values.env.redisHost }}
            - name: REDIS_PASSWORD
              value: {{ .Values.env.redisPassword }}
            - name: REDIS_HOST
              value: {{ .Values.env.redisHost }}
            - name: REDIS_PORT
              value: {{ .Values.env.redisPort }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
