apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xivstatus-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "xivstatus-api.name" . }}
    helm.sh/chart: {{ include "xivstatus-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "xivstatus-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "xivstatus-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        configHash: {{ .Values.configHash }}
        secretHash: {{ .Values.secretHash }}
    spec:
    {{- if .Values.image.auth }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretsName }}
    {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/status
              port: http
          readinessProbe:
            httpGet:
              path: /api/status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: APP_NAME
              value: {{ .Values.envAppName | quote }}
            - name: APP_ENV
              value: {{ .Values.envAppEnv | quote }}
            - name: APP_KEY
              value: {{ .Values.envAppKey | quote }}
            - name: APP_DEBUG
              value: {{ .Values.envAppDebug | quote }}
            - name: APP_URL
              value: {{ .Values.envAppUrl | quote }}
            - name: LOG_CHANNEL
              value: {{ .Values.envLogChannel | quote }}
            - name: DB_CONNECTION
              value: {{ .Values.envDbConnection | quote }}
            - name: DB_HOST
              value: {{ .Values.envDbHost | quote }}
            - name: DB_PORT
              value: {{ .Values.envDbPort | quote }}
            - name: DB_DATABASE
              value: {{ .Values.envDbDatabase | quote }}
            - name: DB_USERNAME
              value: {{ .Values.envDbUsername | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.envDbPassword | quote }}
            - name: REDIS_HOST
              value: {{ .Values.envRedisHost | quote }}
            - name: REDIS_PORT
              value: {{ .Values.envRedisPort | quote }}
            - name: REDIS_PASSWORD
              value: {{ .Values.envRedisPassword | quote }}
            - name: REDIS_PREFIX
              value: ""
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
