apiVersion: batch/v1
kind: Job
metadata:
  name: xivstatus-migrate-database
  namespace: xivstatus
  annotations:
    flux.weave.works/ignore: false
spec:
  template:
    metadata:
      name: xivstatus-migrate-database
    spec:
      imagePullSecrets:
        - name: harbor-regcred
      containers:
      - name: xivstatus-migrate-database
        image: harbor.uptilt.io/defrostedtuna/xivstatus-api:master-ca44156
        imagePullPolicy: Always
        # command: ["php"]
        # args: ["artisan", "migrate:rollback", "--force", "--no-interaction"]
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        envFrom:
        - secretRef:
            name: env-xivstatus-api
        env:
          - name: DB_HOST
            value: "10.10.10.10"
        # Config map values shouldn't matter at this point.
      restartPolicy: Never