apiVersion: batch/v1
kind: Job
metadata:
  name: xivstatus-migrate-database
  namespace: xivstatus
spec:
  template:
    metadata:
      name: xivstatus-migrate-database
    spec:
      imagePullSecrets:
        - name: harbor-regcred
      containers:
      - name: xivstatus-migrate-database
        image: harbor.uptilt.io/defrostedtuna/xivstatus-api:master-ca44156
        imagePullPolicy: Always
        command: ["php"]
        args: ["artisan", "migrate:rollback", "--force", "--no-interaction"]
        envFrom:
        - secretRef:
            name: env-xivstatus-api
        envFrom:
        - configMapRef:
            name: xivstatus-api
      restartPolicy: Never