apiVersion: v1
kind: ConfigMap
metadata:
  name: xivstatus-api
  namespace: xivstatus
data:
  values.yaml: |
    envAppName: "xivstatus-api"
    envAppEnv: "production"
    envAppDebug: false
    envAppUrl: "https://xivstatus-api.uptilt.dev"
    envLogChannel: "stack"