apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: xivstatus-monitor
  namespace: xivstatus
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: xivstatus-monitor
  chart:
    git: git@github.com:defrostedtuna/kubernetes-lordran-dev
    path: charts/xivstatus-monitor
    ref: master
  values:
    image:
      repository: harbor.uptilt.io/defrostedtuna/xivstatus-monitor
      tag: test5
      pullPolicy: Always
      auth: true
      pullSecretsName: harbor-regcred