apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: xivstatus-monitor
  namespace: xivstatus
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: xivstatus-monitor
  chart:
    git: git@github.com:defrostedtuna/kubernetes-lordran-dev
    path: charts/xivstatus-monitor
    ref: master
  valuesFrom:
  - configMapKeyRef:
      name: xivstatus-monitor
  values:
    image:
      repository: harbor.uptilt.io/defrostedtuna/xivstatus-monitor
      tag: master-992edd3
      pullPolicy: Always
      auth: true
      pullSecretsName: harbor-regcred
    configHash: 51758bda1a9cb68238c1f1cd3572f13c3f03c6dfb48e59af517ab93a280bd2c0